### ISSUE TITLE
config.yaml wrong for Universal models

### ISSUE THREAD

**Issue by Vanwalleghem** [HelmchenLabSoftware/Cascade#10]
Hey,

it seems there's a typo in all the config.yaml files for the Universal models, it says they've been trained on (line 13)
```
-DS07-GCaMP6f-zf-dD
```

but the provided ground truth is 

```
DS07-GCaMP6f-zf-OB
```
which one is right?

**Comment by PTRRupprecht** [comment]
Hi Gilles,

Well spotted! When I trained the Universal models, by accident the filename was wrong ('DS07-GCaMP6f-zf-dD'), such that the automatically generated config.yaml file propagated this error. After that, I simply renamed the folder to the correct name ('DS07-GCaMP6f-zf-OB').

I'll check how this typo can be correct for all the dozen of Universal models.

**Comment by PTRRupprecht** [comment]
Is fixed now.
