### ISSUE TITLE
broken link for 'Global_EXC_15Hz_smoothing100ms'

### ISSUE THREAD

**Issue by vdtang3** [HelmchenLabSoftware/Cascade#15]
Hi - I've been unable to download the model named 'Global_EXC_15Hz_smoothing100ms'. Any chance that the link could be updated?

**Comment by PTRRupprecht** [comment]
Hi @vdtang3,
Thanks for the feedback.
We had to recently change the names of all models during the revisions for the paper, but it seems I forgot to update the link for this specific model. The link is fixed now.
- Peter

**Comment by PTRRupprecht** [comment]
Fixed
