### ISSUE TITLE
Discrepancy between DS01-OGB1-m-V1 and SpikeFinder dataset #2

### ISSUE THREAD

**Issue by giovannidiana** [HelmchenLabSoftware/Cascade#28]
I have noticed a difference between the CASCADE dataset DS01-OGB1-m-V1 and the original dataset #2 from the SpikeFinder study. 
The ground-truth spike times seem randomly offset with respect to the fluorescence traces. Would you be able to look into this?

**Comment by PTRRupprecht** [comment]
Hi Giovanni,

As discussed per email, I agree with your finding. I have now re-extracted the ground truth recordings for dataset 1 (DS01-OGB1-m-V1) and uploaded the updated ground truth.

In addition, I have also checked the other datasets for alignment of spikes with respect to calcium, and I have improved the temporal alignment of spikes for dataset 15, where some neurons were slightly misaligned.

Thanks a lot for spotting this mistake.

Best,
Peter
