### ISSUE TITLE
Conflicts in version of packages for local installation (for CPU)

### ISSUE THREAD

**Issue by SimonZamora** [HelmchenLabSoftware/Cascade#29]
Dear Peter,

First of all, thanks for sharing CASCADE with the world. It will help a great number of neuroscientist in their work around the world! :)

I am trying to incorporate CASCADE in my pipeline for peak detection and thus need to install it locally. Unfortunately, I can't manage to find a way to install it using the command on my Anaconda Prompt: ``conda create -n Cascade python=3.6 tensorflow==2.3 keras==2.3.1 h5py==2.10.0 numpy scipy matplotlib seaborn ruamel.yaml spyder``. 

There seems to be (a lot) of conflicts  going on between the version of the various packages needed. 

I have tried to install/uninstall my version of Anaconda (and also update a few packages) without managing to find a way to make everything work together. Could you please give the exact version of each package you are using so I can find a combination of version that allow a smooth installation? 

Thanks a lot for your help! 

Best wishes,

Simon Zamora

PS: Here is an output of all the conflicts in case you want to go through them

(base) C:\Users\simon>conda create -n Cascade python=3.6 tensorflow==2.3 keras==2.3.1 h5py==2.10.0 numpy scipy matplotlib seaborn ruamel.yaml spyder
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining tensorflow==2.3:  42%|███████████████████████▎                                | 5/12 [00:03<00:00, 16.37it/s]-Examining seaborn:  58%|█████████████████████████████████████▎                          | 7/12 [00:03<00:03,  1.66it/s]|Examining matplotlib:  83%|██████████████████████████████████████████████████          | 10/12 [00:06<00:01,  1.27it/s]/Examining conflict for python numpy tensorflow h5py seaborn ruamel.yaml matplotlib scipy spyder:  58%|▌| 7/12 [00:09<00\Examining conflict for python tensorflow:  67%|███████████████████████████▎             | 8/12 [00:11<00:04,  1.20s/it]\failed                                                             /           /                                     |

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
seaborn -> python[version='>=3.6'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
ruamel.yaml -> python[version='>=3.9,<3.10.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
tensorflow==2.3 -> python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
numpy -> python[version='>=3.10,<3.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a']
spyder -> python[version='>=3.10,<3.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a']
h5py==2.10.0 -> python[version='>=3.9,<3.10.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a']
scipy -> python[version='>=3.10,<3.11.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a']

Package python conflicts for:
scipy -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
python=3.6
matplotlib -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
seaborn -> python[version='>=2.7,<2.8.0a0|>=3.6|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
h5py==2.10.0 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
numpy -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
seaborn -> matplotlib[version='>=2.2'] -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7.1,<3.8.0a0']
keras==2.3.1 -> keras-base=2.3.1 -> python[version='3.5.*|3.6.*|3.7.*|3.8.*|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.9.*']
ruamel.yaml -> python[version='>=3.10,<3.11.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
matplotlib -> cycler[version='>=0.10'] -> python[version='>=3.6']
spyder -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
h5py==2.10.0 -> numpy[version='>=1.16.6,<2.0a0'] -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.5,<3.6.0a0']
ruamel.yaml -> ruamel.yaml.clib[version='>=0.1.2'] -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
spyder -> atomicwrites[version='>=1.2.0'] -> python[version='>=2.7|>=3.7|>=3|>=3.5|>=3.6']

Package certifi conflicts for:
ruamel.yaml -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
matplotlib -> tornado -> certifi[version='>=2016.09|>=2016.9.26|>=2020.06.20']
spyder -> setuptools[version='>=49.6.0'] -> certifi[version='>=2016.09|>=2016.9.26']

Package numpy conflicts for:
numpy
matplotlib -> numpy[version='>=1.14.6,<2.0a0']
keras==2.3.1 -> keras-base=2.3.1 -> numpy[version='>=1.9.1']
scipy -> numpy[version='>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.21.2,<2.0a0|>=1.15.1,<2.0a0']
matplotlib -> matplotlib-base[version='>=3.5.0,<3.5.1.0a0'] -> numpy[version='>=1.15.4,<2.0a0|>=1.16.6,<2.0a0|>=1.19.2,<2.0a0|>=1.21.2,<2.0a0']
seaborn -> numpy[version='>=1.13.3|>=1.15|>=1.9.3']
seaborn -> matplotlib[version='>=2.2'] -> numpy[version='>=1.11|>=1.11.3,<1.12.0a0|>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.14.6,<2.0a0|>=1.19.2,<2.0a0|>=1.20.3,<2.0a0|>=1.20.2,<2.0a0|>=1.16.6,<2.0a0|>=1.15.4,<2.0a0|>=1.21.2,<2.0a0|>=1.15.1,<2.0a0|>=1.9|>=1.17.0,<2.0a0|>=1.19.1,<2.0a0|>=1.4.0']
h5py==2.10.0 -> numpy[version='>=1.11.3,<2.0a0|>=1.16.6,<2.0a0']

Package zlib conflicts for:
python=3.6 -> sqlite[version='>=3.33.0,<4.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
tensorflow==2.3 -> tensorflow-base==2.3.0=eigen_py37h17acbac_0 -> zlib[version='>=1.2.11,<1.3.0a0']
scipy -> python[version='>=3.10,<3.11.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
seaborn -> matplotlib[version='>=2.2'] -> zlib[version='>=1.2.11,<1.3.0a0']
numpy -> python[version='>=3.10,<3.11.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
ruamel.yaml -> python[version='>=3.10,<3.11.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
matplotlib -> zlib[version='>=1.2.11,<1.3.0a0']
spyder -> python[version='>=3.10,<3.11.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
h5py==2.10.0 -> hdf5[version='>=1.10.6,<1.10.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package pyqt conflicts for:
seaborn -> matplotlib[version='>=2.2'] -> pyqt[version='5.*|5.6.*|5.9.*|>=5.6,<6.0a0|>=5.9.2,<5.10.0a0']
matplotlib -> pyqt[version='5.*|5.6.*|5.9.*|>=5.6,<6.0a0|>=5.9.2,<5.10.0a0']
spyder -> qtconsole[version='>=4.2'] -> pyqt[version='>=5.9.2,<5.10.0a0']
spyder -> pyqt[version='5.*|>=5.6,<5.13']

Package vs2015_runtime conflicts for:
python=3.6 -> vs2015_runtime[version='>=14.16.27012,<15.0a0']
python=3.6 -> vc[version='>=14.1,<15.0a0'] -> vs2015_runtime[version='>=14.0.25123,<15.0a0|>=14.0.25420|>=14.15.26706|>=14.27.29016|>=14.16.27012']

Package tzdata conflicts for:
spyder -> python[version='>=3.10,<3.11.0a0'] -> tzdata
seaborn -> python[version='>=3.6'] -> tzdata
ruamel.yaml -> python[version='>=3.9,<3.10.0a0'] -> tzdata
h5py==2.10.0 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> tzdata
numpy -> python[version='>=3.10,<3.11.0a0'] -> tzdata
scipy -> python[version='>=3.10,<3.11.0a0'] -> tzdata

Package tensorflow conflicts for:
tensorflow==2.3
keras==2.3.1 -> tensorflow

Package six conflicts for:
keras==2.3.1 -> keras-base=2.3.1 -> six[version='>=1.9.0']
seaborn -> patsy -> six
spyder -> cookiecutter[version='>=1.6.0'] -> six[version='>=1.10|>=1.11.0|>=1.5']
numpy -> mkl-service[version='>=2.3.0,<3.0a0'] -> six
scipy -> mkl-service[version='>=2.3.0,<3.0a0'] -> six
h5py==2.10.0 -> six
matplotlib -> cycler[version='>=0.10'] -> six[version='>=1.5']
tensorflow==2.3 -> tensorboard[version='>=2.3.0'] -> six[version='>=1.10.0|>=1.12|>=1.12.0|>=1.14.0']

Package colorama conflicts for:
python=3.6 -> pip -> colorama
spyder -> ipython[version='>=7.6.0'] -> colorama[version='>=0.3.5']

Package h5py conflicts for:
h5py==2.10.0
keras==2.3.1 -> keras-base=2.3.1 -> h5py

Package matplotlib conflicts for:
seaborn -> matplotlib[version='>=1.4.3|>=2.1.2|>=2.2']
matplotlib

Package numpy-base conflicts for:
numpy -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.2|1.19.2|1.19.2|1.19.2|1.20.1|1.20.1|1.20.1|1.20.2|1.20.2|1.20.2|1.20.3|1.20.3|1.20.3|1.21.2|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|>=1.9.3,<2.0a0|1.17.0|1.17.0',build='py36hc3f5095_0|py37h5c71026_6|py36h5c71026_6|py27h0bb1d87_6|py36h5c71026_7|py36h5c71026_7|py37h5c71026_7|py36h5c71026_8|py35h4a99626_8|py35h4a99626_9|py37h4a99626_9|py37h8128ebf_9|py36h8128ebf_9|py35h8128ebf_9|py35h8128ebf_10|py36h8128ebf_10|py27h2753ae9_10|py27hb1d0314_11|py36h555522e_1|py27h917549b_1|py35h5c71026_0|py36h5c71026_0|py35h5c71026_0|py36h5c71026_0|py37h5c71026_0|py27h0bb1d87_1|py36h5c71026_1|py36h5c71026_2|py37h5c71026_2|py27h0bb1d87_2|py36h5c71026_3|py27h0bb1d87_4|py37h5c71026_4|py36h5c71026_4|py35h4a99626_4|py36h8128ebf_4|py27h2753ae9_4|py35h8128ebf_4|py27hb1d0314_5|py35h4a99626_0|py37h4a99626_0|py35h8128ebf_0|py27h2753ae9_0|py35h8128ebf_0|py27h2753ae9_0|py36h8128ebf_0|py27h2753ae9_1|py27h2753ae9_0|py36hc3f5095_0|py36hc3f5095_0|py27hb1d0314_0|py36hc3f5095_0|py36hc3f5095_0|py27hb1d0314_0|py36hc3f5095_0|py36hc3f5095_0|py36hc3f5095_0|py38hc3f5095_0|py39h2e04a8b_1|py37h5bb6eb2_3|py38ha3acd2a_0|py38ha3acd2a_0|py39hbd0edd7_0|py38haf7ebc8_0|py37hc2deb75_0|py39hc2deb75_0|py37hc2deb75_0|py37h0829f74_0|py310h0829f74_0|py38h0829f74_0|py39h0829f74_0|py39hc2deb75_0|py38hc2deb75_0|py38hc2deb75_0|py39haf7ebc8_0|py37haf7ebc8_0|py36ha3acd2a_0|py37ha3acd2a_0|py36ha3acd2a_0|py37ha3acd2a_0|py38h5bb6eb2_3|py36h5bb6eb2_3|py39h5bb6eb2_3|py27hb1d0314_0|py37hc3f5095_0|py37hc3f5095_0|py27hb1d0314_0|py37hc3f5095_0|py37hc3f5095_0|py36hc3f5095_0|py37hc3f5095_0|py27hb1d0314_0|py27hb1d0314_1|py36hc3f5095_1|py37hc3f5095_1|py37hc3f5095_0|py27hb1d0314_1|py36hc3f5095_1|py37hc3f5095_1|py27hb1d0314_0|py37hc3f5095_0|py37hc3f5095_0|py27hb1d0314_0|py27h2753ae9_0|py36h8128ebf_0|py37h8128ebf_0|py37h8128ebf_0|py36h8128ebf_0|py37h8128ebf_0|py36h8128ebf_0|py37h8128ebf_0|py27hfef472a_0|py36h4a99626_0|py36hc3f5095_5|py37hc3f5095_5|py38hc3f5095_4|py37h8128ebf_4|py37h5c71026_3|py27h0bb1d87_3|py37h5c71026_1|py27h0bb1d87_0|py27h0bb1d87_0|py35h555522e_1|py38hc3f5095_12|py36hc3f5095_12|py27hb1d0314_12|py37hc3f5095_12|py36h2a9b21d_11|py37h2a9b21d_11|py37h8128ebf_11|py36h8128ebf_11|py37h8128ebf_10|py27h2753ae9_9|py27hfef472a_9|py36h4a99626_9|py27h0bb1d87_8|py37h5c71026_8|py27h0bb1d87_7|py35h5c71026_7|py37h5c71026_7|py27h0bb1d87_7|py37hc3f5095_0']
numpy -> mkl_fft -> numpy-base[version='>=1.0.14,<2.0a0|>=1.0.6,<2.0a0|>=1.0.2,<2.0a0|>=1.0.4,<2.0a0']

Package vc conflicts for:
python=3.6 -> vc[version='14.*|>=14.1,<15.0a0']
python=3.6 -> sqlite[version='>=3.30.1,<4.0a0'] -> vc=9

Package setuptools conflicts for:
ruamel.yaml -> setuptools
spyder -> ipython[version='>=7.6.0'] -> setuptools[version='>=18.5']
matplotlib -> setuptools
tensorflow==2.3 -> tensorboard[version='>=2.3.0'] -> setuptools[version='>=41.4']
spyder -> setuptools[version='>=39.0.0|>=49.6.0']
seaborn -> matplotlib[version='>=2.2'] -> setuptools
python=3.6 -> pip -> setuptools

Package sip conflicts for:
matplotlib -> pyqt -> sip[version='4.18.*|4.19.13.*|>=4.19.13,<=4.19.14|>=4.19.4,<=4.19.8']
spyder -> pyqt[version='>=5.6,<5.13'] -> sip[version='4.18.*|4.19.13.*|>=4.19.13,<=4.19.14|>=4.19.4,<=4.19.8']

Package vs2008_runtime conflicts for:
seaborn -> python -> vs2008_runtime
scipy -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime
matplotlib -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime[version='>=9.0.30729.1,<10.0a0']
numpy -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime[version='>=9.0.30729.1,<10.0a0']
spyder -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime

Package mkl conflicts for:
numpy -> mkl_random -> mkl[version='>=2020.1,<2021.0a0']
numpy -> mkl[version='>=2018.0.0,<2019.0a0|>=2018.0.1,<2019.0a0|>=2018.0.2,<2019.0a0|>=2018.0.3,<2019.0a0|>=2019.1,<2021.0a0|>=2019.3,<2021.0a0|>=2019.4,<2021.0a0|>=2021.2.0,<2022.0a0|>=2021.3.0,<2022.0a0|>=2021.4.0,<2022.0a0|>=2019.4,<2020.0a0']

Package pyyaml conflicts for:
spyder -> watchdog[version='>=0.10.3'] -> pyyaml[version='>=3.10']
keras==2.3.1 -> keras-base=2.3.1 -> pyyaml

Package tk conflicts for:
ruamel.yaml -> python[version='>=3.10,<3.11.0a0'] -> tk[version='>=8.6.11,<8.7.0a0']
spyder -> python[version='>=3.10,<3.11.0a0'] -> tk[version='>=8.6.11,<8.7.0a0']
seaborn -> python[version='>=3.6'] -> tk[version='>=8.6.11,<8.7.0a0']
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> tk[version='>=8.6.11,<8.7.0a0']
scipy -> python[version='>=3.10,<3.11.0a0'] -> tk[version='>=8.6.11,<8.7.0a0']
numpy -> python[version='>=3.10,<3.11.0a0'] -> tk[version='>=8.6.11,<8.7.0a0']

Package scipy conflicts for:
scipy
seaborn -> statsmodels[version='>=0.5.0'] -> scipy[version='>=0.14|>=1.3']
keras==2.3.1 -> keras-base=2.3.1 -> scipy[version='>=0.14']
seaborn -> scipy[version='>=0.15.2|>=1.0|>=1.0.1']

Package blas conflicts for:
scipy -> blas[version='*|1.0',build=mkl]
h5py==2.10.0 -> numpy[version='>=1.16.6,<2.0a0'] -> blas[version='*|1.0',build=mkl]
matplotlib -> numpy[version='>=1.14.6,<2.0a0'] -> blas[version='*|1.0',build=mkl]
seaborn -> numpy[version='>=1.15'] -> blas[version='*|1.0',build=mkl]
numpy -> blas[version='*|1.0',build=mkl]

Package packaging conflicts for:
matplotlib -> matplotlib-base[version='>=3.5.0,<3.5.1.0a0'] -> packaging[version='>=20.0']
python=3.6 -> pip -> packaging
spyder -> sphinx[version='>=0.6.6'] -> packaging

Package intel-openmp conflicts for:
numpy -> mkl[version='>=2021.4.0,<2022.0a0'] -> intel-openmp[version='2021.*|2022.*']
scipy -> mkl[version='>=2021.4.0,<2022.0a0'] -> intel-openmp=2021

Package wheel conflicts for:
python=3.6 -> pip -> wheel
tensorflow==2.3 -> tensorboard[version='>=2.3.0'] -> wheel[version='>=0.26']

Package requests conflicts for:
spyder -> cookiecutter[version='>=1.6.0'] -> requests[version='>2.0.0|>=2.0.0|>=2.23.0|>=2.5.0']
tensorflow==2.3 -> tensorboard[version='>=2.3.0'] -> requests[version='>=2.21.0|>=2.21.0,<3']
python=3.6 -> pip -> requests

**Comment by PTRRupprecht** [comment]
Hi Simon,

Thanks for bringing up this issue! I could reproduce your problem both on an Ubuntu and a Windows machine.

I realized that this combination of conda packages worked for me in a specific environment, but it does not seem to work when it is installed from scratch in a new conda environment. That's a problem.

However, the problem can be solved by slightly changing the package specifications and using python 3.7. (3.8 works as well, but let's stick with 3.7 for now.) The following installation command should therefore work for you: ``conda create -n Cascade python=3.7 tensorflow==2.3 keras==2.3.1 h5py numpy scipy matplotlib seaborn ruamel.yaml spyder``
This worked for me on both Ubuntu and Windows.

I'd like to briefly explain why this error occurred in the first place: The original version of Cascade was based on Tensorflow 2.1. However, I recently trained new models using a newer Tensorflow 2.3 version, and there turned out to be no backward-compatibility of models. I therefore decided to update Cascade to Tensorflow 2.3, which resulted in the unexpected conflict between packages when they are freshly installed.

I will update the readme today, and I will keep an eye on these issues when I will make updates to Cascade in the future.

Thanks again for reporting this bug, and I'd be happy if you could let me know whether it worked out for you in the end!

Best wishes,
Peter

**Comment by SimonZamora** [comment]
Oh my! 

Thanks a lot for your swift and precise answer! The installation is now running smoothly on my local machine and I will have the chance to incorporate CASCADE in my pipline :)

I am working on a project looking in calcuim activity in hyppocampal neuronal cultures. I will let you know once, I make some progress so I can share my dataset with you to maybe use it for future work! 

Have a great day,

Simon
