### ISSUE TITLE
info_file_link URL broken

### ISSUE THREAD

**Issue by generalciao** [HelmchenLabSoftware/Cascade#44]
The method download_model in cascade.py has a hardcoded URL, which I think is supposed to allow a file available_models.yaml to be downloaded? But the URL seems to be broken (for me - is it user error?). I get a 503 error from python, and a "Sorry for the short delay" error message in a browser.  https://drive.switch.ch/index.php/s/IJWlhwjDT3aw2ro/download

I ran into this problem while trying to re-follow the collaboratory example steps after I switched to a local installation.

PS: Thanks for this interesting tool!

**Comment by PTRRupprecht** [comment]
Hi @generalciao,

End of 2021, I accidentally overwrote this file on the server and had to recreate it. The download link therefore changed from 
previously:    https://drive.switch.ch/index.php/s/IJWlhwjDT3aw2ro/download
to now:   https://drive.switch.ch/index.php/s/kjGm0qsZdofY629/download

The hardcoded URL was already updated last year in November in ``cascade.py``, so I guess that updating your local repository will fix this backward incompatibility. The URL should also not change in any foreseeable future.

Let me know if you encounter any other problems!

**Comment by generalciao** [comment]
Hi! Thank you very much for the quick response. I confirm that the second (new) link works for me, at least in a browser.

We just installed CASCADE today onto our Linux server, and the cascade.py still has the old (broken) URL. My best guess (?) is that it was installed from the release v1.0.0 tag, instead of the latest master head - I wasn't aware of that. I'll double check with the person who manages the server.

Do you recommend we work from the latest version of the master branch? Or what is your change/testing/tagging/release procedure?

**Comment by PTRRupprecht** [comment]
Hi @generalciao,

Good to know that it works now!

My recommendation would be to work from the latest version of the master branch. I would only make a new release once the architecture or database changes substantially (e.g., addition of GCaMP8 data). If you think that this minimal procedure could create problems or is opposite of best practice, please let me know, then I can think about alternative standard procedures.
