### ISSUE TITLE
Going through traces 1  by 1

### ISSUE THREAD

**Issue by m-artin-p** [HelmchenLabSoftware/Cascade#60]
Hey,

I want to implement the toolbox into our imaging pipeline. For the noise level and/or the inference, is it important to give cascade all traces at once or can I infer them one-by-one with the same results? Our pipeline usually would go through data like that, this is why I am asking.

Thank you in advance,

martin

**Comment by PTRRupprecht** [comment]
By the way, if you are going through neurons one-by-one, it might be useful for you to look into the non-verbose mode, as discussed here, to avoid too much feedback on the command line: https://github.com/HelmchenLabSoftware/Cascade/issues/47

**Comment by m-artin-p** [comment]
That was the answer I was hoping for and at an incredible speed. 
Thank you so much @PTRRupprecht!
And indeed, I already very much appreciate the non-verbose option ;)

**Comment by m-artin-p** [comment]
Analyzing a single trace causes the error as the length of the matrix is accessed incorrectly 

..../cascade2p/utils.py#line=137, in preprocess_traces(neurons_x_time, before_frac, window_size)
    136 dF_traces = neurons_x_time
    137 start = int(before_frac * window_size -1)
--> 138 end = dF_traces.shape[1] - window_size + start + 1

It is an easy fix, but I thought I report it

**Comment by PTRRupprecht** [comment]
Hi @m-artin-p,

It's true that this can happen when using as input an array of singular dimension. As you mentioned, it is easy to fix, e.g., by adding a `line like `traces = np.expand_dims(traces,0)`` before feeding the trace to the algorithm. I now added such a line of code that catches and resolves this case automatically. Thanks for reporting this bug!

Peter

**Comment by m-artin-p** [comment]
Cool! Thank you so much!
